name: 'Custom Task List Approval'
author: 'Afonso Tomás Taborda'
description: 'Create a tasklist'
branding:
  icon: 'check'
  color: 'blue'
inputs:
  token:
    description: 'The Github access token'
    required: true
  comment-title:
    description: 'The title to be added into the comment'
  comment-body:
    description: 'The body of text that comes befores the tasklist items'
  tasklist-items: # Like tasklist item 1;tasklist item 2;random item 3;
    description: 'The user-created tasklist of items'
    required: true
  completion-timeout: # In minutes, defines the timeout of the job
    description: 'If set, it starts a timer and meanwhile verifies that all tasklist items have been completed before the timeout'
  delete-previous-similar-tasklists:
    description: 'If true, it will delete all comments that contains the exact same task list items, except the latest one'
    default: 'false'
  delete-comment-after-completion:
    description: 'If set to true, it deletes the task list comment after completion of the job'
    default: 'true'
  debug-logs:
    description: 'If true, debug-logs logs will be written'
    default: 'true'
runs:
  using: 'node16'
  main: 'index.js'