name: 'Custom Checklist Approval'
author: 'Afonso Tomás Taborda'
description: 'Create a checklist'
branding:
  icon: 'check'  
  color: 'blue'
inputs:
  token:
    description: 'The Github access token'
    required: true
  comment-title:
    description: 'The title to be added into the comment'
  comment-id:
    description: 'The string prefix that denotes the UID for a single comment'
    required: true
  comment-body:
    description: 'The body of text that comes befores the checklist items'
  checklist-items: # Like checklist item 1;checklist item 2;random item 3;
    description: 'The user-created checklist of items'
    required: true
  run-with-timer:
    description: 'If true, then the workflow will use a timer to wait for all task lists in a commment to be completed'
    default: 'true'
  completion-timeout: # In minutes, defines the timeout of the job
    description: 'Only active if `run-with-timer` is set to true. Verifies that all checklist items have been completed before the timeout'
    default: '60'
  delete-comment-after-completion:
    description: 'If set to true, it deletes the task list comment after completion of the job'
    default: 'true'
  debug-logs:
    description: 'If true, debug-logs logs will be written'
    default: 'true'
runs:
  using: 'node16'
  main: 'index.js'