on:
  pull_request:
    branches:    
      - master

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write'
  pull-requests: 'write'

jobs:
  create-checklist:
    runs-on: ubuntu-latest
    name: Create the Checklist
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Custom Checklist Approval
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: "TODO List" # Optional
          comment-header: "TODO List Header" # Optional
          comment-body: "Please finish the TODO list below before moving to the next step:" # Optional
          checklist-items: "Hello World" # Required