on:
  pull_request:
    branches:    
      - master

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write'
  pull-requests: 'write'

jobs:
  create-checklist:
    runs-on: ubuntu-latest
    name: Create the Checklist
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Custom Checklist Approval
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "Hello World"